### ISSUE TITLE
Error analyzing output_saturation

### ISSUE THREAD

**Issue by bhavranek** [Kortemme-Lab/flex_ddG_tutorial#20]
Hello, 

I have used the flex ddG protocol perfectly before. However, this time I am attempting to analyze the results from a saturation mutagenesis run and get the following error while executing:

python3 analyze_flex_ddG.py output_saturation/

Traceback (most recent call last):
  File "analyze_flex_ddG.py", line 215, in <module>
    analyze_output_folder( folder_to_analyze )
  File "analyze_flex_ddG.py", line 194, in analyze_output_folder
    ddg_scores_dfs.append( apply_zemu_gam(ddg_scores) )
  File "analyze_flex_ddG.py", line 40, in apply_zemu_gam
    assert( score_term in scores.columns )
AssertionError

I have used the same protocol for other projects with no issue, but this system is bringing up the error above. 

Any ideas?

**Comment by wangtao111111** [comment]
I also encountered this problem, please ask if this problem has been solved?

**Comment by sajad-stack** [comment]
Same with me. Any suggestion on how to resolve it?

**Comment by kylebarlow** [comment]
Hi all, I am guessing that newer versions of Rosetta are returning different score terms. The GAM model was developed on Talaris score function output, and will only work on those scores. A fix should be to comment out the line  ddg_scores_dfs.append( apply_zemu_gam(ddg_scores) ) that calls apply_zemu_gam. Can anyone confirm if that works?

**Comment by kylebarlow** [comment]
I updated the code to wrap the call to the GAM function in try/except block, which might also fix the issue by leaving out the GAM scores if they can't be run.

**Comment by Sinsilcobio** [comment]
Thank you very much, Kyle!
I commented out the line and seems to be working fine!

**Comment by Sinsilcobio** [comment]
I am not sure if I should ask this question here...
But, I was just wondering if I can use the Flex_ddg for evaluating the effect of the mutations on destabilizing the monomeric protein forms (or does the flx_ddg only work for mutations at the binding interface of two chains?).
If the answer is positive, could you please give me a clue on how I might adopt the protocol for mutations in monomeric proteins?

**Comment by wangtao-cell** [comment]
My problem is solved, my input structure is a protein and a peptide binding complex. My initial input protein structure was faulty, then I docked it using a protein monomer and a peptide fragment, and the docked complex was ready for mutation using flex_ddg.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月17日(星期三) 凌晨5:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kortemme-Lab/flex_ddG_tutorial] Error analyzing output_saturation (Issue #20)





 
Same with me. Any suggestion on how to resolve it?
